import AtiyahAndMacdonald.Base


variable {A B: Type} [CommutativeRing A][ CommutativeRing B]

structure RingHom (A B : Type) [CommutativeRing A] [CommutativeRing B] where
  toFun : A → B
  -- Lean knows `x + y` is in A, and `toFun x + toFun y` is in B
  map_add : ∀ x y : A, toFun (x + y) = toFun x + toFun y
  map_mul : ∀ x y : A, toFun (x * y) = toFun x * toFun y
  map_one : toFun 1 = 1

-- Allows you to use the homomorphism as a normal function `f x`
instance {A B : Type} [CommutativeRing A] [CommutativeRing B] : CoeFun (RingHom A B) (fun _ => A → B) where
  coe f := f.toFun

def kernel {A B : Type} [CommutativeRing A] [CommutativeRing B] (f : RingHom A B) : Set A :=
  { x : A | f x = 0}
---Lemmas for Hom--

theorem zero_in_kernel (f:RingHom A B): f 0= 0:= by
  have : (f 0)+ (f 0)=(f 0):= by
    calc
    (f 0)+(f 0)=f (0+0):= by exact Eq.symm (f.map_add 0 0)
    _= f (0):= by rw[add_zero 0]
  exact add_self_cancel (f.toFun 0) (f.toFun 0) this
theorem fneg_one_to_neg_one (f : RingHom A B) : f (-1) = -(f 1) := by
  calc
    f (-1) = 0 + f (-1) := by rw [add_comm, add_zero]
    _ = (-(f 1) + f 1) + f (-1) := by rw [add_left_neg]
    _ = -(f 1) + (f 1 + f (-1)) := by rw [add_assoc]
    _ = -(f 1) + f (1 + -1) := by rw [← f.map_add]
    _ = -(f 1) + f (-1 + 1) := by rw [add_comm 1 (-1)]
    _ = -(f 1) + f 0 := by rw [add_left_neg]
    _ = -(f 1) + 0 := by rw [zero_in_kernel f]
    _=(-(f 1)):= by rw[add_zero (-(f 1)) ]
theorem fneg_a_neg_fa (f:RingHom A B)(a:A): f (-a)=-(f a):= by
  rw[← neg_one_element a,f.map_mul,fneg_one_to_neg_one,f.map_one,neg_one_element]
theorem hom_npow (f : RingHom A B) (x : A) (k : Nat) : f (x^k) = (f x)^k := by
  induction k with
  | zero =>
    have h1 : x^0 = 1 := by exact ((fun a => a) ∘ fun a => a) rfl
    have h2 : (f x)^0 = 1 := by exact ((fun a => a) ∘ fun a => a) rfl
    rw [h2, h1]
    exact f.map_one
  | succ n ih =>
    change f (x * x^n) = f x * (f x)^n
    rw [f.map_mul, ih]



/-- The contraction of an ideal J ⊆ B along a ring homomorphism f : A → B.
    It is the preimage f⁻¹(J). -/
def ideal_contraction {A B: Type }[CommutativeRing A][CommutativeRing B](f : RingHom A B) (J : Set B) : Set A :=
  { x : A | f x ∈ J }
/-- The extension of an ideal I ⊆ A along a ring homomorphism f : A → B.
    It is the ideal in B generated by the image f(I). -/
def ideal_extension {A B: Type }[CommutativeRing A][CommutativeRing B](f : RingHom A B) (I : Set A) : Set B :=
  ideal_generated_by { y : B | ∃ x ∈ I, f x = y }

--Important Lemmas--
theorem ideal_contraction_is_ideal {A B : Type} [CommutativeRing A] [CommutativeRing B] (f : RingHom A B) (J : Set B) (hJ : IsIdeal J) : IsIdeal (ideal_contraction f J) := by
  simp [ideal_contraction]
  constructor
  simp
  · rw [zero_in_kernel]
    exact hJ.1
  · intro a b ha hb
    simp_all
    rw [f.map_add, fneg_a_neg_fa]
    exact hJ.additive_subgroup (f.toFun a) (f.toFun b) ha hb
  · rintro a _ ⟨a1, b, rfl, hb, rfl⟩
    simp
    rw [f.map_mul]
    apply hJ.3 (f a1)
    exact ⟨f a1, f b, rfl, hb, rfl⟩




theorem pideal_contraction_is_pideal {A B: Type }[CommutativeRing A][CommutativeRing B](f : RingHom A B) (J : Set B) (hJ: IsPrimeIdeal J): IsPrimeIdeal (ideal_contraction f J):= by
  constructor
  simp[ideal_contraction]
  intro x y hxy hy
  rw[f.map_mul x y] at hxy
  exact hJ.1 _ _ hxy hy
  apply ideal_contraction_is_ideal
  exact hJ.2

theorem kernel_is_ideal {A B : Type} [CommutativeRing A] [CommutativeRing B] (f : RingHom A B) : IsIdeal (kernel f) := by
  simp_all[kernel]
  constructor
  exact zero_in_kernel f
  intro a b ha hb
  simp_all
  rw[f.map_add,fneg_a_neg_fa,ha,hb,add_comm, add_zero (-0),← neg_one_element 0,mul_comm,zero_mul]
  intro a y hy
  obtain ⟨a1,⟨b,⟨ha1,⟨hb,hab ⟩⟩⟩⟩:= hy
  simp_all
  rw[← hab,f.map_mul,hb,mul_comm,zero_mul]
