import AtiyahAndMacdonald.Base


variable {A B: Type} [CommutativeRing A][ CommutativeRing B]

structure RingHom (A B : Type) [CommutativeRing A] [CommutativeRing B] where
  toFun : A → B
  -- Lean knows `x + y` is in A, and `toFun x + toFun y` is in B
  map_add : ∀ x y : A, toFun (x + y) = toFun x + toFun y
  map_mul : ∀ x y : A, toFun (x * y) = toFun x * toFun y
  map_one : toFun 1 = 1

-- Allows you to use the homomorphism as a normal function `f x`
instance {A B : Type} [CommutativeRing A] [CommutativeRing B] : CoeFun (RingHom A B) (fun _ => A → B) where
  coe f := f.toFun

def kernel {A B : Type} [CommutativeRing A] [CommutativeRing B] (f : RingHom A B) : Set A :=
  { x : A | f x = 0}
--Lemmas for homomorphisms--
theorem hom_npow (f : RingHom A B) (x : A) (k : Nat) : f (x^k) = (f x)^k := by
  induction k with
  | zero =>
    have h1 : x^0 = 1 := by exact ((fun a => a) ∘ fun a => a) rfl
    have h2 : (f x)^0 = 1 := by exact ((fun a => a) ∘ fun a => a) rfl
    rw [h2, h1]
    exact f.map_one
  | succ n ih =>
    change f (x * x^n) = f x * (f x)^n
    rw [f.map_mul, ih]



/-- The contraction of an ideal J ⊆ B along a ring homomorphism f : A → B.
    It is the preimage f⁻¹(J). -/
def ideal_contraction {A B: Type }[CommutativeRing A][CommutativeRing B](f : RingHom A B) (J : Set B) : Set A :=
  { x : A | f x ∈ J }
theorem ideal_contraction_is_ideal {A B: Type }[CommutativeRing A][CommutativeRing B](f : RingHom A B) (J : Set B) (hJ: IsIdeal J): IsIdeal (ideal_contraction f J):= by
  sorry
theorem pideal_contraction_is_pideal {A B: Type }[CommutativeRing A][CommutativeRing B](f : RingHom A B) (J : Set B) (hJ: IsPrimeIdeal J): IsPrimeIdeal (ideal_contraction f J):= by
  sorry

/-- The extension of an ideal I ⊆ A along a ring homomorphism f : A → B.
    It is the ideal in B generated by the image f(I). -/
def ideal_extension {A B: Type }[CommutativeRing A][CommutativeRing B](f : RingHom A B) (I : Set A) : Set B :=
  ideal_generated_by { y : B | ∃ x ∈ I, f x = y }


theorem kernel_is_ideal {A B : Type} [CommutativeRing A] [CommutativeRing B] (f : RingHom A B) : IsIdeal (kernel f) := by
  sorry
