import AtiyahAndMacdonald.Base
import AtiyahAndMacdonald.Base_Quotient
set_option linter.unusedSimpArgs false

variable {R : Type} [CommutativeRing R]

def IsUnit (x : R) : Prop :=
  ∃ y : R, x * y = 1

def IsZeroDivisor (x : R) : Prop :=
  ∃ y : R, y ≠ 0 ∧ x * y = 0
def isMaximalIdeal (M : Set R) : Prop :=
  (IsIdeal M) ∧ ¬((1 : R) ∈ M) ∧ ∀ I : Set R, IsIdeal I → M ⊆ I → (∀ x, x ∈ I → x ∈ M) ∨ (1 : R) ∈ I

def Radical (I : Set R) : Set R :=
  { x : R | ∃ n : Nat, x ^ n ∈ I }

def Nilradical (R : Type) [CommutativeRing R] : Set R :=
  { x : R | IsNilpotent x }

--Important Collections 2--
def MaximalIdealsof (R:Type)[CommutativeRing R]: Set (Set R):=
{M:Set R|IsMaximalIdeal M}

-- 1. Bounded Family Definitions
/-- Asserts that the first n sets in the sequence P are ideals. -/
def IsIdealFamily (P : ℕ → Set R) (n : ℕ) : Prop :=
  ∀ i < n, IsIdeal (P i)

/-- Asserts that the first n sets in the sequence P are prime ideals. -/
def IsPrimeFamily (P : ℕ → Set R) (n : ℕ) : Prop :=
  ∀ i < n, IsPrimeIdeal (P i)
----

def JacobsonRadical (R : Type) [CommutativeRing R] : Set R :=
  sInter (MaximalIdealsof R)

def ideal_add (I J : Set R) : Set R :=
  { x : R | ∃ a b : R, a ∈ I ∧ b ∈ J ∧ a + b = x }

def AreCoprime (I J : Set R) : Prop :=
  (1 : R) ∈ ideal_add I J

def Annihilator (x : R) : Set R :=
  { y : R | x * y = (0 : R) }

/-- An integral domain is a ring where 1 ≠ 0 and there are no zero-divisors other than 0[cite: 6]. -/
def IsIntegralDomain (R : Type) [CommutativeRing R] : Prop :=
  (1 : R) ≠ (0 : R) ∧ ∀ x : R, IsZeroDivisor x → x = (0 : R)

/-- A field is a ring where 1 ≠ 0 and every non-zero element is a unit[cite: 6]. -/
def IsField (R : Type) [CommutativeRing R] : Prop :=
  (1 : R) ≠ (0 : R) ∧ ∀ x : R, x ≠ (0 : R) → IsUnit x

/-- The product of two ideals is the ideal generated by their element-wise products. -/
def ideal_mul (I J : Set R) : Set R :=
  ideal_generated_by (set_mul I J)

def ideal_prod (P : ℕ → Set R) : ℕ → Set R
  | 0 => Set.univ
  | (n + 1) => ideal_mul (ideal_prod P n) (P n)

def phi_prod (P : ℕ → Set R) (n : ℕ) (hP : IsIdealFamily P n) (x : R) :
    ∀ i (hi : i < n), QuotientRing (P i) (hP i hi) :=
  fun i hi => quotient_pi_hom (P i) (hP i hi) x

def IsLocalRing (R:Type) [CommutativeRing R]: Prop :=
∃I:Set R, MaximalIdealsof R={I}


def colon_ideal (I: Set R ) (J : Set R) : Set R :=
  { x : R | set_mul {x} J ⊆ I}
---Important Lemmas--

theorem isMaximal_eq_IsMaximal (M:Set R): IsMaximalIdeal M ↔ isMaximalIdeal M := by
  simp[IsMaximalIdeal,IsMaximalElement,ProperIdealsOf,isMaximalIdeal]
  constructor
  intro ⟨ ⟨hM1,hM2⟩ , hP⟩
  constructor
  exact hM1
  constructor
  exact hM2
  intro I hI hMI
  have h2: 1∈ I ∨ ¬(1∈I):= by exact Classical.em (1 ∈ I)
  cases h2
  (expose_names; exact Or.inr h)
  constructor!
  intro x hx
  have h: I=M := by
    apply hP
    exact hI
    (expose_names; exact (Set.mem_compl_iff I 1).mp h)
    exact hMI
  rw[← h]
  exact hx
  intro a
  simp_all only [not_false_eq_true, and_self, true_and]
  intro P a_1 a_2 a_3
  obtain ⟨ h2, h3⟩ := a
  obtain ⟨left_1, h4⟩ := h3
  ext x
  constructor
  intro hP
  have := h4 P a_1 a_3
  rcases this
  (expose_names; exact Set.mem_of_subset_of_mem h (a_3 (h x hP)))
  (expose_names; exact Set.not_notMem.mp fun a => a_2 h)
  exact fun a => Set.mem_of_subset_of_mem a_3 a


/-- Lemma: x ∈ r(I) ↔ x̄ ∈ Nilradical(R/I) -/
lemma mem_radical_iff_quotient_nilradical (I : Set R) (hI : IsIdeal I) (x : R) : x ∈ Radical I ↔ quotient_pi_hom I hI x ∈ Nilradical (QuotientRing I hI) := by
  sorry
