import AtiyahAndMacdonald.Base
set_option linter.unusedSimpArgs false

variable {R : Type} [CommutativeRing R]

def IsUnit (x : R) : Prop :=
  ∃ y : R, x * y = 1

def IsZeroDivisor (x : R) : Prop :=
  ∃ y : R, y ≠ 0 ∧ x * y = 0
def isMaximalIdeal (M : Set R) : Prop :=
  (IsIdeal M) ∧ ¬((1 : R) ∈ M) ∧ ∀ I : Set R, IsIdeal I → M ⊆ I → (∀ x, x ∈ I → x ∈ M) ∨ (1 : R) ∈ I

def Radical (I : Set R) : Set R :=
  { x : R | ∃ n : Nat, x ^ n ∈ I }

def Nilradical (R : Type) [CommutativeRing R] : Set R :=
  { x : R | IsNilpotent x }

def JacobsonRadical (R : Type) [CommutativeRing R] : Set R :=
  { x : R | ∀ M : Set R, IsMaximalIdeal M → x ∈ M }

theorem isMaximal_eq_IsMaximal (M:Set R): IsMaximalIdeal M ↔ isMaximalIdeal M := by
  simp[IsMaximalIdeal,IsMaximalElement,ProperIdealsOfR,isMaximalIdeal]
  constructor
  intro ⟨ ⟨hM1,hM2⟩ , hP⟩
  constructor
  exact hM1
  constructor
  exact hM2
  intro I hI hMI
  have h2: 1∈ I ∨ ¬(1∈I):= by exact Classical.em (1 ∈ I)
  cases h2
  (expose_names; exact Or.inr h)
  constructor!
  intro x hx
  have h: I=M := by
    apply hP
    exact hI
    (expose_names; exact (Set.mem_compl_iff I 1).mp h)
    exact hMI
  rw[← h]
  exact hx
  intro a
  simp_all only [not_false_eq_true, and_self, true_and]
  intro P a_1 a_2 a_3
  obtain ⟨ h2, h3⟩ := a
  obtain ⟨left_1, h4⟩ := h3
  ext x
  constructor
  intro hP
  have := h4 P a_1 a_3
  rcases this
  (expose_names; exact Set.mem_of_subset_of_mem h (a_3 (h x hP)))
  (expose_names; exact Set.not_notMem.mp fun a => a_2 h)
  exact fun a => Set.mem_of_subset_of_mem a_3 a

def ideal_add (I J : Set R) : Set R :=
  { x : R | ∃ a b : R, a ∈ I ∧ b ∈ J ∧ a + b = x }

def AreCoprime (I J : Set R) : Prop :=
  (1 : R) ∈ ideal_add I J

def Annihilator (x : R) : Set R :=
  { y : R | x * y = (0 : R) }

def IdealsContaining (I : Set R) : Set (Set R) :=
  { J : Set R | IsIdeal J ∧ I ⊆ J }

def IdealsOfQuotient (I : Set R) (hI : IsIdeal I) : Set (Set (QuotientRing I hI)) :=
  { J' : Set (QuotientRing I hI) | IsIdeal J' }
/-- The kernel is the set of elements in the domain that map to 0 in the codomain. -/
def kernel {A B : Type} [CommutativeRing A] [CommutativeRing B] (f : RingHom A B) : Set A :=
  { x : A | f x = (0 : B) }

/-- An integral domain is a ring where 1 ≠ 0 and there are no zero-divisors other than 0[cite: 6]. -/
def IsIntegralDomain (R : Type) [CommutativeRing R] : Prop :=
  (1 : R) ≠ (0 : R) ∧ ∀ x : R, IsZeroDivisor x → x = (0 : R)

/-- A field is a ring where 1 ≠ 0 and every non-zero element is a unit[cite: 6]. -/
def IsField (R : Type) [CommutativeRing R] : Prop :=
  (1 : R) ≠ (0 : R) ∧ ∀ x : R, x ≠ (0 : R) → IsUnit x
/-- The ideal generated by a set E is the intersection of all ideals containing E. -/
def ideal_generated_by (E : Set R) : Set R :=
  { x : R | ∀ I : Set R, IsIdeal I → E ⊆ I → x ∈ I }

/-- The product of two ideals is the ideal generated by their element-wise products. -/
def ideal_mul (I J : Set R) : Set R :=
  ideal_generated_by (set_mul I J)

theorem ideal_gen_by_is_ideal (E: Set R): IsIdeal (ideal_generated_by E) := by
  let F:= {I:Set R| IsIdeal I ∧  E ⊆ I}
  have hF1: F⊆ IdealsOfR := by
    intro I hI
    exact Set.mem_of_mem_inter_left hI
  have hF2 : ideal_generated_by E={x : R | ∀ I ∈ F, x ∈ I}:= by
    ext x
    simp only [ideal_generated_by]
    constructor
    intro hx I hI
    apply hx
    apply hF1 hI
    apply hI.2
    intro hF I hI EI
    apply hF
    simp[F]
    exact ⟨hI, EI⟩
  rw[hF2]
  exact Arb_int_ideal F hF1
